//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Com.ZimVie.Wcs.Framework.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Com.ZimVie.Wcs.Framework.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cbm Controller is not specified [{0}]. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ffce00001 {
            get {
                return ResourceManager.GetString("ffce00001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Column Name is not specified. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ffce00002 {
            get {
                return ResourceManager.GetString("ffce00002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ConfigurationErrorsException occured in access configuration file{0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ffce00003 {
            get {
                return ResourceManager.GetString("ffce00003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Configuration file not found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ffce00004 {
            get {
                return ResourceManager.GetString("ffce00004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   usersettings data not found in the configuration file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ffce00005 {
            get {
                return ResourceManager.GetString("ffce00005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Data not found for usersettings in the configuration file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ffce00006 {
            get {
                return ResourceManager.GetString("ffce00006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Data not found for the [{0}] in the configuration file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ffce00007 {
            get {
                return ResourceManager.GetString("ffce00007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error occured when kill the process : {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ffce00008 {
            get {
                return ResourceManager.GetString("ffce00008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unhandled exception occured : {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ffce00009 {
            get {
                return ResourceManager.GetString("ffce00009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unexpected error has occurred again while handling unexpected exception. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ffce00010 {
            get {
                return ResourceManager.GetString("ffce00010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error occured when kill the process during application initialization : {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ffce00011 {
            get {
                return ResourceManager.GetString("ffce00011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [APPLICATION_HEADER] [{0}] in the configuration file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ffce00012 {
            get {
                return ResourceManager.GetString("ffce00012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [CONNECTION_STRING] [{0}] in the configuration file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ffce00013 {
            get {
                return ResourceManager.GetString("ffce00013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [AUTHENTIFICATE_FLAG] [{0}] in the configuration file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ffce00014 {
            get {
                return ResourceManager.GetString("ffce00014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [SERVER_TIME_ZONE] [{0}] in the configuration file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ffce00015 {
            get {
                return ResourceManager.GetString("ffce00015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   application configuration setting value is null. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ffce00016 {
            get {
                return ResourceManager.GetString("ffce00016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   application configuration setting data not found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ffce00017 {
            get {
                return ResourceManager.GetString("ffce00017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error occured remote service object creation : {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ffce00018 {
            get {
                return ResourceManager.GetString("ffce00018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connection string is not specified. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ffce00019 {
            get {
                return ResourceManager.GetString("ffce00019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exception occured during password encryption. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ffce00020 {
            get {
                return ResourceManager.GetString("ffce00020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exception occured in wait progress form running. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ffce00021 {
            get {
                return ResourceManager.GetString("ffce00021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Server Connection error : [{0}]. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ffce00022 {
            get {
                return ResourceManager.GetString("ffce00022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ApplicationException occured in cbm execution [{0}]. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ffce00023 {
            get {
                return ResourceManager.GetString("ffce00023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SystemException occured in cbm execution [{0}]. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ffce00024 {
            get {
                return ResourceManager.GetString("ffce00024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unexcepted error occured in cbm execution [{0}]. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ffce00025 {
            get {
                return ResourceManager.GetString("ffce00025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UnhandledException occured in rollback transaction [{0}]. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ffce00026 {
            get {
                return ResourceManager.GetString("ffce00026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exception occured in dbconnection close [{0}]. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ffce00027 {
            get {
                return ResourceManager.GetString("ffce00027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   InvalidOperationException occured in rollback transaction [{0}]. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ffce00028 {
            get {
                return ResourceManager.GetString("ffce00028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [{0}] settings file not found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ffce00029 {
            get {
                return ResourceManager.GetString("ffce00029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [APPLICATION_ENVIRONMENT_SETTINGS] [{0}] in the configuration file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ffce00030 {
            get {
                return ResourceManager.GetString("ffce00030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please provide valid keyname[{0}] in the settings file to get the value. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ffce00031 {
            get {
                return ResourceManager.GetString("ffce00031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NullReferenceException occurs in getting configuration. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ffce00032 {
            get {
                return ResourceManager.GetString("ffce00032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NullReferenceException occurs in getting sectionname from configuration. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ffce00033 {
            get {
                return ResourceManager.GetString("ffce00033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value not found for the [{0}] in the configuration file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ffce00034 {
            get {
                return ResourceManager.GetString("ffce00034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Section not found for the [{0}] in the configuration file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ffce00035 {
            get {
                return ResourceManager.GetString("ffce00035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Element not found for the [{0}] in the configuration file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ffce00036 {
            get {
                return ResourceManager.GetString("ffce00036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [APPLICATION_ENVIRONMENT_HEADER] [{0}] in the configuration file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ffce00037 {
            get {
                return ResourceManager.GetString("ffce00037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please select factory. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ffce00038 {
            get {
                return ResourceManager.GetString("ffce00038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Column Name is not specified in DefaultMySqlParameterList. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ffce00039 {
            get {
                return ResourceManager.GetString("ffce00039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connection string is not specified in MySqlCbmInvoker. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ffce00040 {
            get {
                return ResourceManager.GetString("ffce00040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cbm Controller is not specified [{0}] in MySqlCbmInvoker. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ffce00041 {
            get {
                return ResourceManager.GetString("ffce00041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ApplicationException occured in cbm execution [{0}] in MySqlCbmInvoker. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ffce00042 {
            get {
                return ResourceManager.GetString("ffce00042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SystemException occured in cbm execution [{0}]in MySqlCbmInvoker. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ffce00043 {
            get {
                return ResourceManager.GetString("ffce00043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unexcepted error occured in cbm execution [{0}]in MySqlCbmInvoker. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ffce00044 {
            get {
                return ResourceManager.GetString("ffce00044", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exception occured in dbconnection close [{0}]in MySqlCbmInvoker. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ffce00045 {
            get {
                return ResourceManager.GetString("ffce00045", resourceCulture);
            }
        }
        
        /// <summary>
        ///   InvalidOperationException occured in rollback transaction [{0}]in MySqlCbmInvoker. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ffce00046 {
            get {
                return ResourceManager.GetString("ffce00046", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UnhandledException occured in rollback transaction [{0}]in MySqlCbmInvoker. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ffce00047 {
            get {
                return ResourceManager.GetString("ffce00047", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Applicationsettingsfilename is null in DefaultStaticCachedConfigurationReader. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ffce00048 {
            get {
                return ResourceManager.GetString("ffce00048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Configvaluemap hashtable instance not created in DefaultStaticCachedConfigurationReader. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ffce00049 {
            get {
                return ResourceManager.GetString("ffce00049", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Batchmain settingsfilename is null in BatchStaticCachedConfigurationReader. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ffce00050 {
            get {
                return ResourceManager.GetString("ffce00050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connection string is not specified in SqlServerCbmInvoker. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ffce00051 {
            get {
                return ResourceManager.GetString("ffce00051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cbm Controller is not specified [{0}] in SqlServerCbmInvoker. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ffce00052 {
            get {
                return ResourceManager.GetString("ffce00052", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ApplicationException occured in cbm execution [{0}] in SqlServerCbmInvoker. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ffce00053 {
            get {
                return ResourceManager.GetString("ffce00053", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SystemException occured in cbm execution [{0}]in SqlServerCbmInvoker. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ffce00054 {
            get {
                return ResourceManager.GetString("ffce00054", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unexcepted error occured in cbm execution [{0}]in SqlServerCbmInvoker. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ffce00055 {
            get {
                return ResourceManager.GetString("ffce00055", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exception occured in dbconnection close [{0}]in SqlServerCbmInvoker. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ffce00056 {
            get {
                return ResourceManager.GetString("ffce00056", resourceCulture);
            }
        }
        
        /// <summary>
        ///   InvalidOperationException occured in rollback transaction [{0}]in SqlServerCbmInvoker. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ffce00057 {
            get {
                return ResourceManager.GetString("ffce00057", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UnhandledException occured in rollback transaction [{0}]in SqlServerCbmInvoker. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ffce00058 {
            get {
                return ResourceManager.GetString("ffce00058", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Column Name is not specified in DefaultSqlServerParameterList. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ffce00059 {
            get {
                return ResourceManager.GetString("ffce00059", resourceCulture);
            }
        }
        
        /// <summary>
        ///   USER_NUMBER_DECIMAL_SEPARATOR is null. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ffce00060 {
            get {
                return ResourceManager.GetString("ffce00060", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string llce00001 {
            get {
                return ResourceManager.GetString("llce00001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please input login. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string llce00002 {
            get {
                return ResourceManager.GetString("llce00002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please input Password. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string llce00003 {
            get {
                return ResourceManager.GetString("llce00003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please provide  valid input. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string llce00004 {
            get {
                return ResourceManager.GetString("llce00004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Data not found for the user [{0}]. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string llce00005 {
            get {
                return ResourceManager.GetString("llce00005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please provide valid Menu. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string llce00006 {
            get {
                return ResourceManager.GetString("llce00006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error has occurred in the LDAP authentification process[{0}]. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string llce00007 {
            get {
                return ResourceManager.GetString("llce00007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please provide valid authenticate flag 1, 2, 3 or 4.
        ///Current value :[{0}]. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string llce00008 {
            get {
                return ResourceManager.GetString("llce00008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New password and confirm password not matching. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string llce00009 {
            get {
                return ResourceManager.GetString("llce00009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please input new password . に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string llce00010 {
            get {
                return ResourceManager.GetString("llce00010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please input confirm password. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string llce00011 {
            get {
                return ResourceManager.GetString("llce00011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New password should not be same as old password. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string llce00012 {
            get {
                return ResourceManager.GetString("llce00012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Old password is error.Please input again! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string llce00013 {
            get {
                return ResourceManager.GetString("llce00013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ObjectDisposedException has occurred in the LDAP authentification send request process[{0}]. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string llce00014 {
            get {
                return ResourceManager.GetString("llce00014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ArgumentNullException has occurred in the LDAP authentification send request process[{0}]. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string llce00015 {
            get {
                return ResourceManager.GetString("llce00015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NotSupportedException has occurred in the LDAP authentification send request process[{0}]. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string llce00016 {
            get {
                return ResourceManager.GetString("llce00016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LdapException has occurred in the LDAP authentification send request process[{0}]. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string llce00017 {
            get {
                return ResourceManager.GetString("llce00017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DirectoryOperationException has occurred in the LDAP authentification send request process[{0}]. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string llce00018 {
            get {
                return ResourceManager.GetString("llce00018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ObjectDisposedException has occurred in the LDAP authentification bind request process with network credential[{0}]. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string llce00019 {
            get {
                return ResourceManager.GetString("llce00019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LdapException has occurred in the LDAP authentification bind request process with network credential[{0}]. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string llce00020 {
            get {
                return ResourceManager.GetString("llce00020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   InvalidOperationException has occurred in the LDAP authentification bind request process with network credential[{0}]. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string llce00021 {
            get {
                return ResourceManager.GetString("llce00021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please provide valid ldap authenticate flag to check for target user 0(No) or 1(Yes).
        ///Current value :[{0}]. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string llce00022 {
            get {
                return ResourceManager.GetString("llce00022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User [{0}] specified multiple times for ldap authentificate. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string llce00023 {
            get {
                return ResourceManager.GetString("llce00023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Multiple data exists for same user [{0}] in m_sap_user table. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string llce00024 {
            get {
                return ResourceManager.GetString("llce00024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SystemException in LdapUserAuthentificateForSpecifiedUserAndUpdateSapUserStrategy - Multiple data exists for same user [{0}] in m_ldap_user table. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string llce00025 {
            get {
                return ResourceManager.GetString("llce00025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sap password not updated for the login user [{0}] in m_sap_user table. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string llce00026 {
            get {
                return ResourceManager.GetString("llce00026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invo is null in CheckAndUpdateLdapPasswordForSapUserCbm. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string llce00027 {
            get {
                return ResourceManager.GetString("llce00027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Authentication flag is missing in server setting file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string llce00028 {
            get {
                return ResourceManager.GetString("llce00028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please provide valid authenticate: 1(LDAP), 2(Local DB), 3(LDAP + SAP), 4(LDAP or Local DB), 5(LDAP or Local DB + SAP).
        ///Current value :[{0}]. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string llce00029 {
            get {
                return ResourceManager.GetString("llce00029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User ID, password, or both are not correct. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string llce00030 {
            get {
                return ResourceManager.GetString("llce00030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The user is not registered as SAP user even though the mes user is SAP_password_sync user. Please log in as another user and register the SAP user. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string llce00031 {
            get {
                return ResourceManager.GetString("llce00031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password has been updated successfully. Please login again. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string llci00001 {
            get {
                return ResourceManager.GetString("llci00001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure want to logout ? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string llci00002 {
            get {
                return ResourceManager.GetString("llci00002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please provide valid input in ldap authentificate for specified user. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string llci00003 {
            get {
                return ResourceManager.GetString("llci00003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User [{0}] not specified for ldap authentificate. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string llci00004 {
            get {
                return ResourceManager.GetString("llci00004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User [{0}] not registered in m_sap_user table. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string llci00005 {
            get {
                return ResourceManager.GetString("llci00005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SapUserVo is null or Ldap password and Sap user password is already same for user [{0}]. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string llci00006 {
            get {
                return ResourceManager.GetString("llci00006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User [{0}] specified for ldap authentificate. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string llci00007 {
            get {
                return ResourceManager.GetString("llci00007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SapUserVo is null for user [{0}] in CheckAndUpdateLdapPasswordForSapUserCbm. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string llci00008 {
            get {
                return ResourceManager.GetString("llci00008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Login user text is blank. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string llci00009 {
            get {
                return ResourceManager.GetString("llci00009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Login password text is blank. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string llci00010 {
            get {
                return ResourceManager.GetString("llci00010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User name, password, or both are not correct. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string llci00011 {
            get {
                return ResourceManager.GetString("llci00011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap NIDEC_Logo_small {
            get {
                object obj = ResourceManager.GetObject("NIDEC_Logo_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap ZimmerBiometLogo {
            get {
                object obj = ResourceManager.GetObject("ZimmerBiometLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap ZimmerBiometLogo1 {
            get {
                object obj = ResourceManager.GetObject("ZimmerBiometLogo1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap ZimmerBiometLogo2 {
            get {
                object obj = ResourceManager.GetObject("ZimmerBiometLogo2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
